# BUILD ARMBIAN IMAGE
name: Build Armbian Image

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Armbian Artifacts
        uses: actions/cache@v4
        with:
          path: build/.cache
          key: ${{ runner.os }}-armbian-uefi-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-armbian-uefi-

      - name: Build Image
        uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "uefi-arm64"
          # CHANGE THIS: Switching to a stable release guarantees pre-compiled repo packages exist
          armbian_release: "trixie" 
          armbian_target: "current"
          armbian_extra_args: 'REPOSITORY_INSTALL="u-boot,kernel,bsp,armbian-firmware" CLEAN_LEVEL="" ARTIFACT_IGNORE_CACHE=no USE_PREBUILT_KERNEL=yes BUILD_MINIMAL=yes KERNEL_CONFIGURE=no'

      - name: Upload Image Artifact to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: compiled-armbian-image
          path: [ "build/output/images/*", "**/output/images/*" ]
          if-no-files-found: error
          retention-days: 5