name: Build Armbian Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: armbian/build@main
        with:
          armbian_board: "uefi-arm64"
          armbian_release: "trixie"
          armbian_target: "build"